
services:

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
    environment:
      - DB_HOST=react_app
      - DB_PORT=5431

    ports:
      - "8000:8000"

    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    # depends_on:
    #   - mqtt-broker
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5431:5431"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # mqtt_broker:
  #   image: eclipse-mosquitto:2.0.21
  #   container_name: mqtt-broker
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./mosquitto.conf:./mosquitto.conf
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: