CREATE TABLE IF NOT EXISTS graph_data (
    timestamp TIMESTAMP WITHOUT TIME ZONE PRIMARY KEY NOT NULL,
    x_value INTEGER NOT NULL,
    y_value INTEGER NOT NULL
)

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
