CREATE TABLE IF NOT EXISTS graph_data (
    timestamp  TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
    y_value INTEGER NOT NULL
)

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
